import "./layout.shared.js";

const {
  MOBILE_BREAKPOINT,
  TABLET_BREAKPOINT,
  getEffectiveViewportWidth,
  getLayoutMode,
  getLayoutDensityTokens,
  hasLayoutModeChanged,
  getStrategySelectionKey,
  ensureStrategyIds,
  buildMobileSummaryCards,
  buildMobileDetailCards,
  getSummaryRenderMode,
  getDetailViewRenderMode,
  getDetailViewToggleLabel,
  getInitialSectionOpenState,
  getResponsiveSectionOpenState,
  buildCompactStatusItems,
  buildToolbarActionGroups,
  buildSummaryTableCells,
  buildDetailTableCells,
  buildCollectionCardFields,
  buildMobileCollectionCardFields,
  buildCollectionCardHeader,
  getMainlineTimelinePresentation,
  buildMainlineScatterData,
  clampFloatingDialogPosition,
} = globalThis.NikkeLayout;

export {
  MOBILE_BREAKPOINT,
  TABLET_BREAKPOINT,
  getEffectiveViewportWidth,
  getLayoutMode,
  getLayoutDensityTokens,
  hasLayoutModeChanged,
  getStrategySelectionKey,
  ensureStrategyIds,
  buildMobileSummaryCards,
  buildMobileDetailCards,
  getSummaryRenderMode,
  getDetailViewRenderMode,
  getDetailViewToggleLabel,
  getInitialSectionOpenState,
  getResponsiveSectionOpenState,
  buildCompactStatusItems,
  buildToolbarActionGroups,
  buildSummaryTableCells,
  buildDetailTableCells,
  buildCollectionCardFields,
  buildMobileCollectionCardFields,
  buildCollectionCardHeader,
  getMainlineTimelinePresentation,
  buildMainlineScatterData,
  clampFloatingDialogPosition,
};
